language: node_js
node_js:
  - "6.11.0"
before_install:
  - "curl https://install.meteor.com | /bin/sh"
install:
  - npm install -g @smallstack/cli
services:
  - mongodb
env:
  - SMALLSTACK_API_KEY=$SMALLSTACK_API_KEY
script: 
  - smallstack setup --mode=url --url=https://s3.eu-central-1.amazonaws.com/smallstack-releases/smallstack-0.9.0-RC6.zip 
  - smallstack generate
  - smallstack bundle
  - smallstack upload
notifications:
  email:
    recipients:
      - infrastructure@smallstack.io
